# Generated by Django 4.2.7 on 2024-03-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldetail",
            name="contact_no",
            field=models.CharField(max_length=100),
        ),
    ]
