# Generated by Django 4.2.7 on 2024-03-16 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_academicperformance_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.faculty_login"
            ),
        ),
        migrations.AlterField(
            model_name="coursestaught",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.faculty_login"
            ),
        ),
    ]
