# Generated by Django 4.2.7 on 2024-03-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_award_user_alter_coursestaught_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldetail",
            name="dob",
            field=models.DateField(null=True),
        ),
    ]
