# Generated by Django 4.2.7 on 2024-04-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_personaldetail_dob"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Archive",
        ),
        migrations.AddField(
            model_name="faculty_login",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faculty_login",
            name="edit_granted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faculty_login",
            name="edit_request_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
