# Generated by Django 5.0.3 on 2024-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_login',
            name='edit_expiry_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='faculty_login',
            name='edit_grant_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
