# Generated by Django 5.0.3 on 2024-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faculty_login_edit_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
