# Generated by Django 5.0.3 on 2024-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_course_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Theory-Cum-Practical', 'Theory-Cum-Practical')], default='Theory', max_length=40),
        ),
    ]
