# Generated by Django 5.0.3 on 2024-05-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='proof',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
